package com.obelisco.modelo.data.seguridad;

import java.util.HashSet;
import java.util.Set;

import com.obelisco.modelo.data.DataGenerica;

/**
 * Operacion generated by MyEclipse - Hibernate Tools
 */
public class Operacion extends DataGenerica implements java.io.Serializable {

	// Fields

	private String codigo;

	private String nombre;

	private Boolean desistema = false;

	private String permiso = "-";

	private Archivo icono = new Archivo();

	private Integer orden = new Integer(10);

	// Constructors

	/** default constructor */
	public Operacion() {
	}

	/** full constructor */
	public Operacion(String codigo, String nombre, String permiso, String estado) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.permiso = permiso;
		setEstado(estado);
	}

	// Property accessors

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPermiso() {
		return this.permiso;
	}

	public void setPermiso(String permiso) {
		this.permiso = permiso;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return getNombre();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codigo == null) ? 0 : codigo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Operacion other = (Operacion) obj;
		if (codigo == null) {
			if (other.codigo != null)
				return false;
		} else if (!codigo.equals(other.codigo))
			return false;
		return true;
	}

	public Archivo getIcono() {
		return icono;
	}

	public void setIcono(Archivo icono) {
		this.icono = icono;
		if (this.icono != null) {
			// this.icono.setNombre("foto.jpg");
			if (this.icono.getContenido().length > 0) {
				this.icono
						.setTipo(Archivo.determinarTipo(icono.getContenido()));
			} else {
				this.icono.setContenido(new byte[] {});
				this.icono.setTipo("");
			}
		} else {
			this.icono = new Archivo();
		}
	}

	public Boolean getDesistema() {
		return desistema;
	}

	public void setDesistema(Boolean desistema) {
		this.desistema = desistema;
	}

	public Integer getOrden() {
		return orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

}
